version: '3.8'

services:
  grpc-server:
    build: .
    ports:
      - "50051:50051"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=your_redis_password
      - REDIS_TTL=3600
      - GRPC_HOST=[::]
      - GRPC_PORT=50051
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - ./src/temp:/app/temp
    networks:
      - shared_network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_redis_password
    volumes:
      - redis_data:/data
    networks:
      - shared_network

volumes:
  redis_data:

networks:
<<<<<<< HEAD
  shared_network:
=======
  shared-network:
>>>>>>> 7379b8086ed71e7aa42b040c93e4bad26e83810e
    external: true